name: full_pension_server
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  sqlite3: ^2.4.0
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.8.0